// S2 — the two colour tables that live in TypeScript (type badges, rarity
// borders) exposed as ready-to-write stylesheets. build.js bundles this
// module and emits the strings below to dist/type-badges.css and
// dist/rarity-borders.css, so the pages link real CSS instead of shipping JS
// just to paint base colours — while TYPE_BADGES / RARITY_COLORS stay the one
// place a colour is ever written down.
//
// This file is build-only: nothing under src/ imports it at runtime.
import { getTypeBadgeCssRules } from './type-badges'
import { getRarityBorderCssRules, getRarityCssVariables } from './rarity-colors'

const GENERATED_NOTE =
  '/* Generated by build.js from src/common/*.ts — do not edit here;\n' +
  '   edit type-badges.ts / rarity-colors.ts and rebuild. */\n'

export const TYPE_BADGES_CSS = `${GENERATED_NOTE}${getTypeBadgeCssRules()}\n`

// ":root" carries the colours as variables (pokedex.css needs them for the
// hover and active variants, which no generator can know about) plus the
// plain border rules for the card base state.
export const RARITY_BORDERS_CSS = `${GENERATED_NOTE}:root {\n${getRarityCssVariables()}\n}\n\n${getRarityBorderCssRules(
  '.pokemon-card'
)}\n`
